### ISSUE TITLE
apollo service:check not working with localSchemaFile

### ISSUE THREAD

**Issue by jbraithwaite** [apollostack/apollo-codegen#1526]
**Intended outcome:**

That `apollo service:check` works with the `localSchemaFile` flag

```bash
npx apollo service:check --localSchemaFile=XXX/schema.graphql --tag=XXX --key="XXX"
```

**Actual outcome:**

```
  ✔ Loading Apollo Project
  ✖ Validating schema against tag XXX on graph XXX
    → Unable to read file XXX/schema.graphql. path must be a string or Buffer
    Comparing schema changes
    Reporting result
Error: Unable to read file XXX/schema.graphql. path must be a string or Buffer
    at FileSchemaProvider.loadFileAndGetDocument (~/.npm/_npx/51975/lib/node_modules/apollo/node_modules/apollo-language-server/lib/providers/schema/file.js:35:19)
    at FileSchemaProvider.resolveSchema (~/.npm/_npx/51975/lib/node_modules/apollo/node_modules/apollo-language-server/lib/providers/schema/file.js:16:21)
    at GraphQLServiceProject.resolveSchema (~/.npm/_npx/51975/lib/node_modules/apollo/node_modules/apollo-language-server/lib/project/base.js:67:36)
    at Task.task (~/.npm/_npx/51975/lib/node_modules/apollo/lib/commands/service/check.js:229:56)    at Promise.resolve.then.then.skipped (~/.npm/_npx/51975/lib/node_modules/apollo/node_modules/listr/lib/task.js:167:30)
    at <anonymous>
```

**How to reproduce the issue:**

Run the command above.

For the command to work:

```bash
npx apollo@2.18.1 service:check --localSchemaFile=XXX/schema.graphql --tag=XXX --key="XXX"
```

**Versions**

`apollo@2.18.2`
`node v8.15.1`
`npx@6.9.0`
`OS X 10.14.6 (18G87)` 
`GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)`

**Comment by martinfranek** [comment]
Encountering same issue since yesterday.

**Comment by gerwim** [comment]
Yes, same issue. Issue is present in `apollo/2.18.2` and not present in `apollo/2.18.1`.
