### ISSUE TITLE
Cannot find module 'process' & version issues

### ISSUE THREAD

**Issue by MaximusMcCann** [apollostack/apollo-codegen#7]
I see 0.8.0 is installed, but it still gives me errors

```
npm install -g apollo-codegen
/usr/local/bin/apollo-codegen -> /usr/local/lib/node_modules/apollo-codegen/lib/cli.js
apollo-codegen@0.8.0 /usr/local/lib/node_modules/apollo-codegen
```

In Xcode:
```
Error: Cannot find module 'process'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/apollo-codegen/lib/cli.js:20:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
error: The version of Apollo.framework in your project requires the use of version 0.8 of apollo-codegen, but an unknown older version seems to be installed.
```

Many variants of `apollo-codegen -version` fail with the same error as above.
Please advise.

Cheers

**Comment by MaximusMcCann** [comment]
Had to `brew update node`
